// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Uh31D6ch51g-34KoQOH--Dy2tQbxlEI',
    appId: '1:739820857737:web:538356831bb5f348b8d958',
    messagingSenderId: '739820857737',
    projectId: 'socialmedia-dddbd',
    authDomain: 'socialmedia-dddbd.firebaseapp.com',
    storageBucket: 'socialmedia-dddbd.appspot.com',
    measurementId: 'G-5YS2DZTYGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ0fiQpbJtGveeBuk9xsWCM1LmAGaXoh0',
    appId: '1:739820857737:android:ff15cd0c56347270b8d958',
    messagingSenderId: '739820857737',
    projectId: 'socialmedia-dddbd',
    storageBucket: 'socialmedia-dddbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZlEMUPY8V36N9OkNxlAogGGTFBdRv6qU',
    appId: '1:739820857737:ios:900447f574042424b8d958',
    messagingSenderId: '739820857737',
    projectId: 'socialmedia-dddbd',
    storageBucket: 'socialmedia-dddbd.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
